functionsDirectory = "/Users/jasonzb/Desktop/apollo/route-manager/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/jasonzb/Desktop/apollo/route-manager/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
node_bundler = "esbuild"
functions = "/Users/jasonzb/Desktop/apollo/route-manager/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
port = 8888.0
functions = "netlify/functions"
publish = "dist"

[dev.environment]
AMADEUS_API_KEY = "${AMADEUS_API_KEY}"
AMADEUS_API_SECRET = "${AMADEUS_API_SECRET}"
AMADEUS_HOSTNAME = "${AMADEUS_HOSTNAME}"
DB_USER = "${DB_USER}"
DB_PASSWORD = "${DB_PASSWORD}"
DB_NAME = "${DB_NAME}"
DB_HOST = "${DB_HOST}"
DB_PORT = "${DB_PORT}"

[functions]

[functions.environment]
AMADEUS_API_KEY = "${AMADEUS_API_KEY}"
AMADEUS_API_SECRET = "${AMADEUS_API_SECRET}"
AMADEUS_HOSTNAME = "${AMADEUS_HOSTNAME}"
DB_USER = "${DB_USER}"
DB_PASSWORD = "${DB_PASSWORD}"
DB_NAME = "${DB_NAME}"
DB_HOST = "${DB_HOST}"
DB_PORT = "${DB_PORT}"

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]