version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: routeuser
      POSTGRES_PASSWORD: routepass
      POSTGRES_DB: routedb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U routeuser -d routedb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
